# Generated by Django 6.0.3 on 2026-04-22 13:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('renewable_energy_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbon_saved_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_saved', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RenewableSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('solar', 'Solar Panel'), ('wind', 'Wind Turbine'), ('hydro', 'Hydroelectric'), ('other', 'Other')], max_length=20)),
                ('capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenewableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_generated', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewable.renewablesource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
