# Generated by Django 6.0.4 on 2026-04-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbonsavings',
            options={'ordering': ['-date'], 'verbose_name': 'Carbon Savings', 'verbose_name_plural': 'Carbon Savings'},
        ),
        migrations.AlterModelOptions(
            name='renewablesource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='renewabledata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='renewable.renewablesource'),
        ),
        migrations.AlterField(
            model_name='renewablesource',
            name='source_type',
            field=models.CharField(choices=[('SOLAR', 'Solar Panel'), ('WIND', 'Wind Turbine'), ('HYDRO', 'Hydroelectric'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
