# Generated by Django 4.2 on 2026-04-27 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewable', '0002_alter_carbonsavings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonsavings',
            name='carbon_saved_kg',
            field=models.FloatField(help_text='CO2 saved in kg', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carbonsavings',
            name='cost_saved',
            field=models.FloatField(help_text='Cost saved in currency units', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carbonsavings',
            name='renewable_energy_kwh',
            field=models.FloatField(help_text='Energy from renewable sources in kWh', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='renewabledata',
            name='efficiency',
            field=models.FloatField(default=0, help_text='Efficiency percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='renewabledata',
            name='power_generated',
            field=models.FloatField(help_text='Power generated in Watts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='renewablesource',
            name='capacity',
            field=models.FloatField(help_text='Capacity in kW', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
