# Generated by Django 6.0.4 on 2026-04-22 18:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='main_device', help_text='Unique identifier for the device', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', help_text='Current status of the device', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='Last time status was updated')),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Device Status',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnergyPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('predicted_power', models.FloatField(help_text='Predicted power consumption in Watts')),
                ('predicted_timestamp', models.DateTimeField(help_text='When this prediction is for')),
                ('confidence_score', models.FloatField(help_text='Confidence level (0-1)', validators=[django.core.validators.MinValueValidator(0)])),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Energy Prediction',
                'ordering': ['-predicted_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RenewableEnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(choices=[('SOLAR', 'Solar'), ('WIND', 'Wind'), ('HYDRO', 'Hydroelectric'), ('OTHER', 'Other')], max_length=10)),
                ('power_generated', models.FloatField(help_text='Power generated in Watts', validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency_percentage', models.FloatField(help_text='Generation efficiency (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Renewable Energy Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_VOLTAGE', 'High Voltage'), ('LOW_VOLTAGE', 'Low Voltage'), ('HIGH_CURRENT', 'High Current'), ('HIGH_POWER', 'High Power'), ('ANOMALY', 'Anomaly Detected'), ('RENEWABLE_EVENT', 'Renewable Energy Event')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('ACKNOWLEDGED', 'Acknowledged')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(help_text='Voltage in Volts', validators=[django.core.validators.MinValueValidator(0)])),
                ('current', models.FloatField(help_text='Current in Amps', validators=[django.core.validators.MinValueValidator(0)])),
                ('power', models.FloatField(help_text='Power in Watts', validators=[django.core.validators.MinValueValidator(0)])),
                ('device_on', models.BooleanField(default=True, help_text='Whether the device was on during measurement')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the measurement was recorded')),
            ],
            options={
                'verbose_name': 'Energy Data',
                'verbose_name_plural': 'Energy Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='energy_ener_timesta_9edf04_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnergyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('average_power', models.FloatField()),
                ('peak_power', models.FloatField()),
                ('minimum_power', models.FloatField()),
                ('total_energy', models.FloatField(help_text='Total energy in kWh')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Energy Trend',
                'ordering': ['-timestamp'],
                'unique_together': {('period', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('enable_sms_alerts', models.BooleanField(default=True)),
                ('enable_email_alerts', models.BooleanField(default=True)),
                ('alert_threshold_power', models.FloatField(default=400)),
                ('alert_threshold_voltage', models.FloatField(default=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
