# Generated by Django 6.0.3 on 2026-04-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EneryData',
            new_name='EnergyData',
        ),
    ]
