# Generated by Django 6.0.3 on 2026-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_rename_enerydata_energydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydata',
            name='device_on',
            field=models.BooleanField(default=True),
        ),
    ]
