# Generated by Django 6.0.3 on 2026-04-05 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_energydata_device_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='main_device', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Device Status',
            },
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Energy Data', 'verbose_name_plural': 'Energy Data'},
        ),
        migrations.AlterField(
            model_name='energydata',
            name='current',
            field=models.FloatField(help_text='Current in Amps', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='power',
            field=models.FloatField(help_text='Power in Watts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='voltage',
            field=models.FloatField(help_text='Voltage in Volts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
