# Generated by Django 6.0.3 on 2026-04-22 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_devicestatus_alter_energydata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('voltage_high', 'High Voltage'), ('voltage_low', 'Low Voltage'), ('power_high', 'High Power'), ('power_low', 'Low Power')], help_text='Type of alert', max_length=50)),
                ('threshold', models.FloatField(help_text='Threshold value for alert', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this alert is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], max_length=50)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Device Status', 'verbose_name_plural': 'Device Status'},
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='device_id',
            field=models.CharField(default='main_device', help_text='Unique identifier for the device', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='status',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='on', help_text='Current status of the device', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Last time status was updated'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='device_on',
            field=models.BooleanField(default=True, help_text='Whether the device was on during measurement'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the measurement was recorded'),
        ),
        migrations.AddIndex(
            model_name='energydata',
            index=models.Index(fields=['-timestamp'], name='energy_ener_timesta_9edf04_idx'),
        ),
    ]
